// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db_gen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	Created                  pgtype.Timestamptz `db:"created" json:"created"`
	Modified                 pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted                  pgtype.Timestamptz `db:"deleted" json:"deleted"`
	IsSystem                 bool               `db:"is_system" json:"isSystem"`
	FirstName                pgtype.Text        `db:"first_name" json:"firstName"`
	LastName                 pgtype.Text        `db:"last_name" json:"lastName"`
	AccessLevel              pgtype.Int4        `db:"access_level" json:"accessLevel"`
	CreditBalance            float64            `db:"credit_balance" json:"creditBalance"`
	Username                 string             `db:"username" json:"username"`
	UserEmailAddress         string             `db:"user_email_address" json:"userEmailAddress"`
	UserAvatarUrl            pgtype.Text        `db:"user_avatar_url" json:"userAvatarUrl"`
	UserZoneInfo             pgtype.Text        `db:"user_zone_info" json:"userZoneInfo"`
	UserLocale               pgtype.Text        `db:"user_locale" json:"userLocale"`
	UserPassword             pgtype.Text        `db:"user_password" json:"userPassword"`
	IsLocked                 bool               `db:"is_locked" json:"isLocked"`
	LastLogin                pgtype.Timestamptz `db:"last_login" json:"lastLogin"`
	ResetPasswordToken       pgtype.Text        `db:"reset_password_token" json:"resetPasswordToken"`
	ResetPasswordTokenExpiry pgtype.Timestamptz `db:"reset_password_token_expiry" json:"resetPasswordTokenExpiry"`
}

type Blog struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted     pgtype.Timestamptz `db:"deleted" json:"deleted"`
	DomainID    pgtype.UUID        `db:"domain_id" json:"domainId"`
	AccountID   pgtype.UUID        `db:"account_id" json:"accountId"`
	PageID      pgtype.UUID        `db:"page_id" json:"pageId"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	Image       string             `db:"image" json:"image"`
	ImageInfo   string             `db:"image_info" json:"imageInfo"`
	Keywords    []string           `db:"keywords" json:"keywords"`
	IsActive    bool               `db:"is_active" json:"isActive"`
}

type BookingRef struct {
	ID       pgtype.UUID        `db:"id" json:"id"`
	Created  pgtype.Timestamptz `db:"created" json:"created"`
	Modified pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted  pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Prefix   string             `db:"prefix" json:"prefix"`
	Initial  int64              `db:"initial" json:"initial"`
	Length   int32              `db:"length" json:"length"`
	Sequence int64              `db:"sequence" json:"sequence"`
}

type Cart struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted       pgtype.Timestamptz `db:"deleted" json:"deleted"`
	CartSessionID string             `db:"cart_session_id" json:"cartSessionId"`
	DomainID      pgtype.UUID        `db:"domain_id" json:"domainId"`
	Completed     bool               `db:"completed" json:"completed"`
}

type CartItem struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Created              pgtype.Timestamptz `db:"created" json:"created"`
	Modified             pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted              pgtype.Timestamptz `db:"deleted" json:"deleted"`
	CartID               pgtype.UUID        `db:"cart_id" json:"cartId"`
	AssociatedCartItemID pgtype.UUID        `db:"associated_cart_item_id" json:"associatedCartItemId"`
	ItemID               pgtype.UUID        `db:"item_id" json:"itemId"`
	ItemType             string             `db:"item_type" json:"itemType"`
	LineCode             string             `db:"line_code" json:"lineCode"`
	Description          string             `db:"description" json:"description"`
	Quantity             pgtype.Numeric     `db:"quantity" json:"quantity"`
	Price                pgtype.Numeric     `db:"price" json:"price"`
	Discount             pgtype.Numeric     `db:"discount" json:"discount"`
	Data                 string             `db:"data" json:"data"`
	RuleHandler          string             `db:"rule_handler" json:"ruleHandler"`
	IsDiscount           bool               `db:"is_discount" json:"isDiscount"`
}

type Commission struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted     pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Code        string             `db:"code" json:"code"`
	Purpose     string             `db:"purpose" json:"purpose"`
	OperatorID  pgtype.UUID        `db:"operator_id" json:"operatorId"`
	Type        string             `db:"type" json:"type"`
	Value       pgtype.Numeric     `db:"value" json:"value"`
	Description pgtype.Text        `db:"description" json:"description"`
	IsActive    bool               `db:"is_active" json:"isActive"`
}

type Component struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Created             pgtype.Timestamptz `db:"created" json:"created"`
	Modified            pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted             pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Name                string             `db:"name" json:"name"`
	Icon                string             `db:"icon" json:"icon"`
	Description         string             `db:"description" json:"description"`
	ClassName           string             `db:"class_name" json:"className"`
	HtmlTag             string             `db:"html_tag" json:"htmlTag"`
	ChildTagConstraints []string           `db:"child_tag_constraints" json:"childTagConstraints"`
	IsActive            bool               `db:"is_active" json:"isActive"`
}

type ComponentField struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Created      pgtype.Timestamptz `db:"created" json:"created"`
	Modified     pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted      pgtype.Timestamptz `db:"deleted" json:"deleted"`
	ComponentID  pgtype.UUID        `db:"component_id" json:"componentId"`
	Name         string             `db:"name" json:"name"`
	Description  string             `db:"description" json:"description"`
	DataType     string             `db:"data_type" json:"dataType"`
	EditorType   string             `db:"editor_type" json:"editorType"`
	Validation   string             `db:"validation" json:"validation"`
	DefaultValue string             `db:"default_value" json:"defaultValue"`
	IsActive     bool               `db:"is_active" json:"isActive"`
}

type Content struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted     pgtype.Timestamptz `db:"deleted" json:"deleted"`
	DomainID    pgtype.UUID        `db:"domain_id" json:"domainId"`
	ComponentID pgtype.UUID        `db:"component_id" json:"componentId"`
	AccountID   pgtype.UUID        `db:"account_id" json:"accountId"`
	Title       string             `db:"title" json:"title"`
	Slug        string             `db:"slug" json:"slug"`
	Data        string             `db:"data" json:"data"`
	IsActive    bool               `db:"is_active" json:"isActive"`
}

type ContentCollection struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Created   pgtype.Timestamptz `db:"created" json:"created"`
	Modified  pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted   pgtype.Timestamptz `db:"deleted" json:"deleted"`
	ParentID  pgtype.UUID        `db:"parent_id" json:"parentId"`
	ContentID pgtype.UUID        `db:"content_id" json:"contentId"`
	Ordering  int32              `db:"ordering" json:"ordering"`
	IsActive  bool               `db:"is_active" json:"isActive"`
}

type Domain struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Created            pgtype.Timestamptz `db:"created" json:"created"`
	Modified           pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted            pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Name               string             `db:"name" json:"name"`
	Description        pgtype.Text        `db:"description" json:"description"`
	IsCmsControlled    bool               `db:"is_cms_controlled" json:"isCmsControlled"`
	IsUnderMaintenance bool               `db:"is_under_maintenance" json:"isUnderMaintenance"`
	IsActive           bool               `db:"is_active" json:"isActive"`
}

type Extension struct {
	ID       pgtype.UUID        `db:"id" json:"id"`
	Created  pgtype.Timestamptz `db:"created" json:"created"`
	Modified pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted  pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Name     string             `db:"name" json:"name"`
	Slug     string             `db:"slug" json:"slug"`
	Icon     string             `db:"icon" json:"icon"`
	Data     string             `db:"data" json:"data"`
	IsActive bool               `db:"is_active" json:"isActive"`
}

type Extra struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted     pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Name        pgtype.Text        `db:"name" json:"name"`
	BannerImage pgtype.Text        `db:"banner_image" json:"bannerImage"`
	Code        pgtype.Text        `db:"code" json:"code"`
	Description pgtype.Text        `db:"description" json:"description"`
	UnitPrice   pgtype.Numeric     `db:"unit_price" json:"unitPrice"`
	IsActive    bool               `db:"is_active" json:"isActive"`
}

type ExtraLocation struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Created    pgtype.Timestamptz `db:"created" json:"created"`
	Modified   pgtype.Timestamptz `db:"modified" json:"modified"`
	ExtraID    pgtype.UUID        `db:"extra_id" json:"extraId"`
	LocationID pgtype.UUID        `db:"location_id" json:"locationId"`
}

type ExtraOperator struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Created    pgtype.Timestamptz `db:"created" json:"created"`
	Modified   pgtype.Timestamptz `db:"modified" json:"modified"`
	ExtraID    pgtype.UUID        `db:"extra_id" json:"extraId"`
	OperatorID pgtype.UUID        `db:"operator_id" json:"operatorId"`
}

type ExtraProductType struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	ExtraID       pgtype.UUID        `db:"extra_id" json:"extraId"`
	ProductTypeID pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
}

type FareSearch struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Created              pgtype.Timestamptz `db:"created" json:"created"`
	Modified             pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted              pgtype.Timestamptz `db:"deleted" json:"deleted"`
	ProductTypeID        pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
	RouteStartLocationID pgtype.UUID        `db:"route_start_location_id" json:"routeStartLocationId"`
	RouteEndLocationID   pgtype.UUID        `db:"route_end_location_id" json:"routeEndLocationId"`
	TravelDate           pgtype.Timestamptz `db:"travel_date" json:"travelDate"`
	IsReturn             bool               `db:"is_return" json:"isReturn"`
	AdultCount           int32              `db:"adult_count" json:"adultCount"`
	ChildCount           int32              `db:"child_count" json:"childCount"`
	InfantCount          int32              `db:"infant_count" json:"infantCount"`
}

type FareSearchResult struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Created            pgtype.Timestamptz `db:"created" json:"created"`
	Modified           pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted            pgtype.Timestamptz `db:"deleted" json:"deleted"`
	FareSearchID       pgtype.UUID        `db:"fare_search_id" json:"fareSearchId"`
	ProductTypeID      pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
	RouteStartLocation string             `db:"route_start_location" json:"routeStartLocation"`
	RouteEndLocation   string             `db:"route_end_location" json:"routeEndLocation"`
	FareDate           pgtype.Timestamptz `db:"fare_date" json:"fareDate"`
	IsReturn           bool               `db:"is_return" json:"isReturn"`
}

type FareSearchResultAvailability struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Created             pgtype.Timestamptz `db:"created" json:"created"`
	Modified            pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted             pgtype.Timestamptz `db:"deleted" json:"deleted"`
	FareSearchResultID  pgtype.UUID        `db:"fare_search_result_id" json:"fareSearchResultId"`
	Token               pgtype.Text        `db:"token" json:"token"`
	FareDate            pgtype.Timestamptz `db:"fare_date" json:"fareDate"`
	Available           bool               `db:"available" json:"available"`
	AvailabilityStatus  string             `db:"availability_status" json:"availabilityStatus"`
	ServiceName         string             `db:"service_name" json:"serviceName"`
	DepartureCity       string             `db:"departure_city" json:"departureCity"`
	DepartureCityInfo   string             `db:"departure_city_info" json:"departureCityInfo"`
	ArrivalCity         string             `db:"arrival_city" json:"arrivalCity"`
	ArrivalCityInfo     string             `db:"arrival_city_info" json:"arrivalCityInfo"`
	DepartureTime       pgtype.Timestamptz `db:"departure_time" json:"departureTime"`
	ArrivalTime         pgtype.Timestamptz `db:"arrival_time" json:"arrivalTime"`
	FareType            string             `db:"fare_type" json:"fareType"`
	FareTypeDescription string             `db:"fare_type_description" json:"fareTypeDescription"`
	AdultPrice          pgtype.Numeric     `db:"adult_price" json:"adultPrice"`
	ChildPrice          pgtype.Numeric     `db:"child_price" json:"childPrice"`
	InfantPrice         pgtype.Numeric     `db:"infant_price" json:"infantPrice"`
	Description         string             `db:"description" json:"description"`
	TicketConditions    string             `db:"ticket_conditions" json:"ticketConditions"`
}

type FareType struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Created         pgtype.Timestamptz `db:"created" json:"created"`
	Modified        pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted         pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Name            string             `db:"name" json:"name"`
	Ordering        int32              `db:"ordering" json:"ordering"`
	Description     string             `db:"description" json:"description"`
	IsInternational bool               `db:"is_international" json:"isInternational"`
	IsActive        bool               `db:"is_active" json:"isActive"`
}

type FareTypeProductType struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	FareTypeID    pgtype.UUID        `db:"fare_type_id" json:"fareTypeId"`
	ProductTypeID pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
}

type FileMeta struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Created             pgtype.Timestamptz `db:"created" json:"created"`
	FileStoreID         pgtype.UUID        `db:"file_store_id" json:"fileStoreId"`
	Key                 string             `db:"key" json:"key"`
	Value               pgtype.Text        `db:"value" json:"value"`
	AttachedFileStoreID pgtype.UUID        `db:"attached_file_store_id" json:"attachedFileStoreId"`
}

type FileStore struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Created             pgtype.Timestamptz `db:"created" json:"created"`
	Modified            pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted             pgtype.Timestamptz `db:"deleted" json:"deleted"`
	IsSystem            bool               `db:"is_system" json:"isSystem"`
	Filename            string             `db:"filename" json:"filename"`
	StoredFilename      string             `db:"stored_filename" json:"storedFilename"`
	ContentType         pgtype.Text        `db:"content_type" json:"contentType"`
	FileSize            int64              `db:"file_size" json:"fileSize"`
	Browsable           bool               `db:"browsable" json:"browsable"`
	Secure              bool               `db:"secure" json:"secure"`
	CompletedProcessing bool               `db:"completed_processing" json:"completedProcessing"`
}

type FileTag struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	FileStoreID pgtype.UUID        `db:"file_store_id" json:"fileStoreId"`
	Tag         string             `db:"tag" json:"tag"`
}

type Location struct {
	ID       pgtype.UUID        `db:"id" json:"id"`
	Created  pgtype.Timestamptz `db:"created" json:"created"`
	Modified pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted  pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Name     string             `db:"name" json:"name"`
	Code     string             `db:"code" json:"code"`
	Ordering int32              `db:"ordering" json:"ordering"`
	IsActive bool               `db:"is_active" json:"isActive"`
}

type Operator struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Created             pgtype.Timestamptz `db:"created" json:"created"`
	Modified            pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted             pgtype.Timestamptz `db:"deleted" json:"deleted"`
	OperatorName        string             `db:"operator_name" json:"operatorName"`
	LocationID          pgtype.UUID        `db:"location_id" json:"locationId"`
	OperatorCode        pgtype.Text        `db:"operator_code" json:"operatorCode"`
	InstructionCust     pgtype.Text        `db:"instruction_cust" json:"instructionCust"`
	EmailAddress        pgtype.Text        `db:"email_address" json:"emailAddress"`
	OperatorDescription pgtype.Text        `db:"operator_description" json:"operatorDescription"`
	OperatorBio         pgtype.Text        `db:"operator_bio" json:"operatorBio"`
	VideoUrl            pgtype.Text        `db:"video_url" json:"videoUrl"`
	StarRating          int32              `db:"star_rating" json:"starRating"`
	OperatorImage       pgtype.Text        `db:"operator_image" json:"operatorImage"`
	WebsiteUrl          pgtype.Text        `db:"website_url" json:"websiteUrl"`
	ZoneInfo            string             `db:"zone_info" json:"zoneInfo"`
	Locale              string             `db:"locale" json:"locale"`
	FareUrl             string             `db:"fare_url" json:"fareUrl"`
	Phone               string             `db:"phone" json:"phone"`
	IsPassCode          bool               `db:"is_pass_code" json:"isPassCode"`
	IsActive            bool               `db:"is_active" json:"isActive"`
}

type OperatorDomain struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Created    pgtype.Timestamptz `db:"created" json:"created"`
	Modified   pgtype.Timestamptz `db:"modified" json:"modified"`
	OperatorID pgtype.UUID        `db:"operator_id" json:"operatorId"`
	DomainID   pgtype.UUID        `db:"domain_id" json:"domainId"`
}

type OperatorProductType struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	OperatorID    pgtype.UUID        `db:"operator_id" json:"operatorId"`
	ProductTypeID pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
}

type Package struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	Created               pgtype.Timestamptz `db:"created" json:"created"`
	Modified              pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted               pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Title                 string             `db:"title" json:"title"`
	Slug                  string             `db:"slug" json:"slug"`
	Code                  string             `db:"code" json:"code"`
	Introduction          string             `db:"introduction" json:"introduction"`
	HeroImage             string             `db:"hero_image" json:"heroImage"`
	HeroImageInfo         string             `db:"hero_image_info" json:"heroImageInfo"`
	Duration              string             `db:"duration" json:"duration"`
	RequiredDeposit       pgtype.Numeric     `db:"required_deposit" json:"requiredDeposit"`
	Departs               string             `db:"departs" json:"departs"`
	Destinations          []string           `db:"destinations" json:"destinations"`
	Route                 []string           `db:"route" json:"route"`
	Description           string             `db:"description" json:"description"`
	IncludedDescription   string             `db:"included_description" json:"includedDescription"`
	ActivitiesDescription string             `db:"activities_description" json:"activitiesDescription"`
	JourneyMap            string             `db:"journey_map" json:"journeyMap"`
	IslandFilter          string             `db:"island_filter" json:"islandFilter"`
	Keywords              string             `db:"keywords" json:"keywords"`
	IsGroupJourney        bool               `db:"is_group_journey" json:"isGroupJourney"`
	IsActive              bool               `db:"is_active" json:"isActive"`
}

type PackageAvailability struct {
	ID            pgtype.UUID          `db:"id" json:"id"`
	Created       pgtype.Timestamptz   `db:"created" json:"created"`
	Modified      pgtype.Timestamptz   `db:"modified" json:"modified"`
	PackageID     pgtype.UUID          `db:"package_id" json:"packageId"`
	Frequency     string               `db:"frequency" json:"frequency"`
	StartDate     pgtype.Timestamptz   `db:"start_date" json:"startDate"`
	EndDate       pgtype.Timestamptz   `db:"end_date" json:"endDate"`
	ExcludedDates []pgtype.Timestamptz `db:"excluded_dates" json:"excludedDates"`
	SoldOutDates  []pgtype.Timestamptz `db:"sold_out_dates" json:"soldOutDates"`
}

type PackageDomains struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Created   pgtype.Timestamptz `db:"created" json:"created"`
	Modified  pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageID pgtype.UUID        `db:"package_id" json:"packageId"`
	DomainID  pgtype.UUID        `db:"domain_id" json:"domainId"`
}

type PackageImages struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Created   pgtype.Timestamptz `db:"created" json:"created"`
	Modified  pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageID pgtype.UUID        `db:"package_id" json:"packageId"`
	Ordering  int32              `db:"ordering" json:"ordering"`
	Image     string             `db:"image" json:"image"`
	ImageInfo string             `db:"image_info" json:"imageInfo"`
}

type PackageIncludedActivities struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageID     pgtype.UUID        `db:"package_id" json:"packageId"`
	Ordering      int32              `db:"ordering" json:"ordering"`
	Title         string             `db:"title" json:"title"`
	Description   pgtype.Text        `db:"description" json:"description"`
	HeroImage     string             `db:"hero_image" json:"heroImage"`
	HeroImageInfo string             `db:"hero_image_info" json:"heroImageInfo"`
	IsActive      bool               `db:"is_active" json:"isActive"`
}

type PackageIncludedItems struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageID   pgtype.UUID        `db:"package_id" json:"packageId"`
	Ordering    int32              `db:"ordering" json:"ordering"`
	Type        string             `db:"type" json:"type"`
	Description pgtype.Text        `db:"description" json:"description"`
	ItemIcon    string             `db:"item_icon" json:"itemIcon"`
	IsActive    bool               `db:"is_active" json:"isActive"`
}

type PackageItinerary struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Created      pgtype.Timestamptz `db:"created" json:"created"`
	Modified     pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageID    pgtype.UUID        `db:"package_id" json:"packageId"`
	Day          int32              `db:"day" json:"day"`
	Title        string             `db:"title" json:"title"`
	EventIcon    string             `db:"event_icon" json:"eventIcon"`
	StationID    pgtype.UUID        `db:"station_id" json:"stationId"`
	Latitude     pgtype.Float8      `db:"latitude" json:"latitude"`
	Longitude    pgtype.Float8      `db:"longitude" json:"longitude"`
	Description  string             `db:"description" json:"description"`
	Supplier     pgtype.Text        `db:"supplier" json:"supplier"`
	SupplierCode pgtype.Text        `db:"supplier_code" json:"supplierCode"`
}

type PackageItineraryImages struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Created            pgtype.Timestamptz `db:"created" json:"created"`
	Modified           pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageItineraryID pgtype.UUID        `db:"package_itinerary_id" json:"packageItineraryId"`
	Ordering           int32              `db:"ordering" json:"ordering"`
	Image              string             `db:"image" json:"image"`
	ImageInfo          string             `db:"image_info" json:"imageInfo"`
	IsActive           bool               `db:"is_active" json:"isActive"`
}

type PackageItineraryNotes struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Created            pgtype.Timestamptz `db:"created" json:"created"`
	Modified           pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageItineraryID pgtype.UUID        `db:"package_itinerary_id" json:"packageItineraryId"`
	Note               string             `db:"note" json:"note"`
}

type PackagePricing struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageID     pgtype.UUID        `db:"package_id" json:"packageId"`
	Supplement    string             `db:"supplement" json:"supplement"`
	AdultPrice    pgtype.Numeric     `db:"adult_price" json:"adultPrice"`
	ChildPrice    pgtype.Numeric     `db:"child_price" json:"childPrice"`
	InfantPrice   pgtype.Numeric     `db:"infant_price" json:"infantPrice"`
	StartDate     pgtype.Timestamptz `db:"start_date" json:"startDate"`
	EndDate       pgtype.Timestamptz `db:"end_date" json:"endDate"`
	SpecificTerms string             `db:"specific_terms" json:"specificTerms"`
}

type PackageTermsConditions struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Created         pgtype.Timestamptz `db:"created" json:"created"`
	Modified        pgtype.Timestamptz `db:"modified" json:"modified"`
	PackageID       pgtype.UUID        `db:"package_id" json:"packageId"`
	GeneralTerms    pgtype.Text        `db:"general_terms" json:"generalTerms"`
	LuggageNotes    pgtype.Text        `db:"luggage_notes" json:"luggageNotes"`
	AdditionalNotes pgtype.Text        `db:"additional_notes" json:"additionalNotes"`
}

type Page struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Created        pgtype.Timestamptz `db:"created" json:"created"`
	Modified       pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted        pgtype.Timestamptz `db:"deleted" json:"deleted"`
	DomainID       pgtype.UUID        `db:"domain_id" json:"domainId"`
	AccountID      pgtype.UUID        `db:"account_id" json:"accountId"`
	ContentID      pgtype.UUID        `db:"content_id" json:"contentId"`
	PagePathID     pgtype.UUID        `db:"page_path_id" json:"pagePathId"`
	Title          string             `db:"title" json:"title"`
	Slug           string             `db:"slug" json:"slug"`
	SeoTitle       string             `db:"seo_title" json:"seoTitle"`
	SeoDescription string             `db:"seo_description" json:"seoDescription"`
	SeoKeywords    string             `db:"seo_keywords" json:"seoKeywords"`
	DraftPageID    pgtype.UUID        `db:"draft_page_id" json:"draftPageId"`
	PageTemplateID pgtype.UUID        `db:"page_template_id" json:"pageTemplateId"`
	PublishAt      pgtype.Timestamptz `db:"publish_at" json:"publishAt"`
	UnpublishAt    pgtype.Timestamptz `db:"unpublish_at" json:"unpublishAt"`
	Version        int32              `db:"version" json:"version"`
	IsActive       bool               `db:"is_active" json:"isActive"`
}

type PagePath struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	Created          pgtype.Timestamptz `db:"created" json:"created"`
	Modified         pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted          pgtype.Timestamptz `db:"deleted" json:"deleted"`
	DomainID         pgtype.UUID        `db:"domain_id" json:"domainId"`
	AccountID        pgtype.UUID        `db:"account_id" json:"accountId"`
	ParentPagePathID pgtype.UUID        `db:"parent_page_path_id" json:"parentPagePathId"`
	Title            string             `db:"title" json:"title"`
	Slug             string             `db:"slug" json:"slug"`
	IsActive         bool               `db:"is_active" json:"isActive"`
}

type PagePathExtension struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	PagePathID  pgtype.UUID        `db:"page_path_id" json:"pagePathId"`
	ExtensionID pgtype.UUID        `db:"extension_id" json:"extensionId"`
}

type PageTemplate struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	Created          pgtype.Timestamptz `db:"created" json:"created"`
	Modified         pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted          pgtype.Timestamptz `db:"deleted" json:"deleted"`
	DomainID         pgtype.UUID        `db:"domain_id" json:"domainId"`
	AccountID        pgtype.UUID        `db:"account_id" json:"accountId"`
	ContentID        pgtype.UUID        `db:"content_id" json:"contentId"`
	ParentPagePathID pgtype.UUID        `db:"parent_page_path_id" json:"parentPagePathId"`
	Title            string             `db:"title" json:"title"`
	Slug             string             `db:"slug" json:"slug"`
	Description      string             `db:"description" json:"description"`
	IsActive         bool               `db:"is_active" json:"isActive"`
}

type Pass struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted       pgtype.Timestamptz `db:"deleted" json:"deleted"`
	ParentPassID  pgtype.UUID        `db:"parent_pass_id" json:"parentPassId"`
	Name          string             `db:"name" json:"name"`
	Code          string             `db:"code" json:"code"`
	OperatorCodes []string           `db:"operator_codes" json:"operatorCodes"`
	Duration      int32              `db:"duration" json:"duration"`
	DurationType  string             `db:"duration_type" json:"durationType"`
	Image         string             `db:"image" json:"image"`
	ImageInfo     string             `db:"image_info" json:"imageInfo"`
	Description   string             `db:"description" json:"description"`
	IsPopular     bool               `db:"is_popular" json:"isPopular"`
	IsTopUp       bool               `db:"is_top_up" json:"isTopUp"`
	Ordering      int32              `db:"ordering" json:"ordering"`
	IsActive      bool               `db:"is_active" json:"isActive"`
}

type PassAvailability struct {
	ID            pgtype.UUID          `db:"id" json:"id"`
	Created       pgtype.Timestamptz   `db:"created" json:"created"`
	Modified      pgtype.Timestamptz   `db:"modified" json:"modified"`
	PassID        pgtype.UUID          `db:"pass_id" json:"passId"`
	StartDate     pgtype.Timestamptz   `db:"start_date" json:"startDate"`
	EndDate       pgtype.Timestamptz   `db:"end_date" json:"endDate"`
	ExcludedDates []pgtype.Timestamptz `db:"excluded_dates" json:"excludedDates"`
	Notes         pgtype.Text          `db:"notes" json:"notes"`
	IsActive      bool                 `db:"is_active" json:"isActive"`
}

type PassAvailabilityPricing struct {
	ID                 pgtype.UUID          `db:"id" json:"id"`
	Created            pgtype.Timestamptz   `db:"created" json:"created"`
	Modified           pgtype.Timestamptz   `db:"modified" json:"modified"`
	PassAvailabilityID pgtype.UUID          `db:"pass_availability_id" json:"passAvailabilityId"`
	FareTypeID         pgtype.UUID          `db:"fare_type_id" json:"fareTypeId"`
	AdultPrice         pgtype.Numeric       `db:"adult_price" json:"adultPrice"`
	ChildPrice         pgtype.Numeric       `db:"child_price" json:"childPrice"`
	InfantPrice        pgtype.Numeric       `db:"infant_price" json:"infantPrice"`
	StartDate          pgtype.Timestamptz   `db:"start_date" json:"startDate"`
	EndDate            pgtype.Timestamptz   `db:"end_date" json:"endDate"`
	ExcludedDates      []pgtype.Timestamptz `db:"excluded_dates" json:"excludedDates"`
}

type PassDomain struct {
	ID       pgtype.UUID        `db:"id" json:"id"`
	Created  pgtype.Timestamptz `db:"created" json:"created"`
	Modified pgtype.Timestamptz `db:"modified" json:"modified"`
	PassID   pgtype.UUID        `db:"pass_id" json:"passId"`
	DomainID pgtype.UUID        `db:"domain_id" json:"domainId"`
}

type PassItinerary struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	PassID      pgtype.UUID        `db:"pass_id" json:"passId"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	Terms       string             `db:"terms" json:"terms"`
}

type PassProductType struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	PassID        pgtype.UUID        `db:"pass_id" json:"passId"`
	ProductTypeID pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
	Category      string             `db:"category" json:"category"`
}

type PassService struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Created      pgtype.Timestamptz `db:"created" json:"created"`
	Modified     pgtype.Timestamptz `db:"modified" json:"modified"`
	PassID       pgtype.UUID        `db:"pass_id" json:"passId"`
	Name         string             `db:"name" json:"name"`
	Duration     int32              `db:"duration" json:"duration"`
	DurationType string             `db:"duration_type" json:"durationType"`
}

type Product struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Created         pgtype.Timestamptz `db:"created" json:"created"`
	Modified        pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted         pgtype.Timestamptz `db:"deleted" json:"deleted"`
	ProductTypeID   pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
	OperatorID      pgtype.UUID        `db:"operator_id" json:"operatorId"`
	StartLocationID pgtype.UUID        `db:"start_location_id" json:"startLocationId"`
	EndLocationID   pgtype.UUID        `db:"end_location_id" json:"endLocationId"`
	Name            string             `db:"name" json:"name"`
	StartPlace      pgtype.Text        `db:"start_place" json:"startPlace"`
	EndPlace        pgtype.Text        `db:"end_place" json:"endPlace"`
	OperatorCode    pgtype.Text        `db:"operator_code" json:"operatorCode"`
	Instructions    pgtype.Text        `db:"instructions" json:"instructions"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	IsActive        pgtype.Bool        `db:"is_active" json:"isActive"`
}

type ProductType struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted       pgtype.Timestamptz `db:"deleted" json:"deleted"`
	Name          string             `db:"name" json:"name"`
	Priority      int32              `db:"priority" json:"priority"`
	Slug          string             `db:"slug" json:"slug"`
	Terms         string             `db:"terms" json:"terms"`
	IsPassType    bool               `db:"is_pass_type" json:"isPassType"`
	IsPassService bool               `db:"is_pass_service" json:"isPassService"`
	IsActive      bool               `db:"is_active" json:"isActive"`
}

type ProductTypeDomain struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	ProductTypeID pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
	DomainID      pgtype.UUID        `db:"domain_id" json:"domainId"`
}

type Service struct {
	ID              pgtype.UUID          `db:"id" json:"id"`
	Created         pgtype.Timestamptz   `db:"created" json:"created"`
	Modified        pgtype.Timestamptz   `db:"modified" json:"modified"`
	Deleted         pgtype.Timestamptz   `db:"deleted" json:"deleted"`
	OperatorID      pgtype.UUID          `db:"operator_id" json:"operatorId"`
	ProductTypeID   pgtype.UUID          `db:"product_type_id" json:"productTypeId"`
	Name            string               `db:"name" json:"name"`
	SubServiceName  pgtype.Text          `db:"sub_service_name" json:"subServiceName"`
	StartLocationID pgtype.UUID          `db:"start_location_id" json:"startLocationId"`
	EndLocationID   pgtype.UUID          `db:"end_location_id" json:"endLocationId"`
	StartStationID  pgtype.UUID          `db:"start_station_id" json:"startStationId"`
	EndStationID    pgtype.UUID          `db:"end_station_id" json:"endStationId"`
	Logo            pgtype.Text          `db:"logo" json:"logo"`
	BannerImage     pgtype.Text          `db:"banner_image" json:"bannerImage"`
	ExcludedDates   []pgtype.Timestamptz `db:"excluded_dates" json:"excludedDates"`
	SoldOutDates    []pgtype.Timestamptz `db:"sold_out_dates" json:"soldOutDates"`
	IsPopular       bool                 `db:"is_popular" json:"isPopular"`
	WithPass        bool                 `db:"with_pass" json:"withPass"`
	IsTour          bool                 `db:"is_tour" json:"isTour"`
	TourName        pgtype.Text          `db:"tour_name" json:"tourName"`
	Description     pgtype.Text          `db:"description" json:"description"`
	DayExcursion    bool                 `db:"day_excursion" json:"dayExcursion"`
	MultiService    bool                 `db:"multi_service" json:"multiService"`
	ExcursionText   pgtype.Text          `db:"excursion_text" json:"excursionText"`
	ServiceCode     pgtype.Text          `db:"service_code" json:"serviceCode"`
	MetaTitle       pgtype.Text          `db:"meta_title" json:"metaTitle"`
	MetaContent     pgtype.Text          `db:"meta_content" json:"metaContent"`
	IsActive        bool                 `db:"is_active" json:"isActive"`
}

type ServiceDomain struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Created   pgtype.Timestamptz `db:"created" json:"created"`
	Modified  pgtype.Timestamptz `db:"modified" json:"modified"`
	ServiceID pgtype.UUID        `db:"service_id" json:"serviceId"`
	DomainID  pgtype.UUID        `db:"domain_id" json:"domainId"`
}

type ServiceNote struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Created   pgtype.Timestamptz `db:"created" json:"created"`
	Modified  pgtype.Timestamptz `db:"modified" json:"modified"`
	ServiceID pgtype.UUID        `db:"service_id" json:"serviceId"`
	Note      string             `db:"note" json:"note"`
}

type ServiceRoute struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Created        pgtype.Timestamptz `db:"created" json:"created"`
	Modified       pgtype.Timestamptz `db:"modified" json:"modified"`
	ServiceID      pgtype.UUID        `db:"service_id" json:"serviceId"`
	ProductID      pgtype.UUID        `db:"product_id" json:"productId"`
	StartStationID pgtype.UUID        `db:"start_station_id" json:"startStationId"`
	EndStationID   pgtype.UUID        `db:"end_station_id" json:"endStationId"`
	IsMainRoute    bool               `db:"is_main_route" json:"isMainRoute"`
	IsPopular      bool               `db:"is_popular" json:"isPopular"`
	IcRouteID      pgtype.Text        `db:"ic_route_id" json:"icRouteId"`
	ShortName      pgtype.Text        `db:"short_name" json:"shortName"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Url            pgtype.Text        `db:"url" json:"url"`
	Color          pgtype.Text        `db:"color" json:"color"`
	TextColor      pgtype.Text        `db:"text_color" json:"textColor"`
	IsActive       bool               `db:"is_active" json:"isActive"`
}

type ServiceRouteAvailability struct {
	ID             pgtype.UUID          `db:"id" json:"id"`
	Created        pgtype.Timestamptz   `db:"created" json:"created"`
	Modified       pgtype.Timestamptz   `db:"modified" json:"modified"`
	ServiceRouteID pgtype.UUID          `db:"service_route_id" json:"serviceRouteId"`
	DepartureTime  pgtype.Timestamptz   `db:"departure_time" json:"departureTime"`
	ArrivalTime    pgtype.Timestamptz   `db:"arrival_time" json:"arrivalTime"`
	Frequency      string               `db:"frequency" json:"frequency"`
	StartDate      pgtype.Timestamptz   `db:"start_date" json:"startDate"`
	EndDate        pgtype.Timestamptz   `db:"end_date" json:"endDate"`
	ExcludedDates  []pgtype.Timestamptz `db:"excluded_dates" json:"excludedDates"`
	SoldOutDates   []pgtype.Timestamptz `db:"sold_out_dates" json:"soldOutDates"`
	CiTimeID       pgtype.Text          `db:"ci_time_id" json:"ciTimeId"`
	Notes          pgtype.Text          `db:"notes" json:"notes"`
	IsActive       bool                 `db:"is_active" json:"isActive"`
}

type ServiceRoutePricing struct {
	ID                         pgtype.UUID          `db:"id" json:"id"`
	Created                    pgtype.Timestamptz   `db:"created" json:"created"`
	Modified                   pgtype.Timestamptz   `db:"modified" json:"modified"`
	ServiceRouteAvailabilityID pgtype.UUID          `db:"service_route_availability_id" json:"serviceRouteAvailabilityId"`
	FareTypeID                 pgtype.UUID          `db:"fare_type_id" json:"fareTypeId"`
	PriceType                  string               `db:"price_type" json:"priceType"`
	AdultPrice                 pgtype.Numeric       `db:"adult_price" json:"adultPrice"`
	ChildPrice                 pgtype.Numeric       `db:"child_price" json:"childPrice"`
	InfantPrice                pgtype.Numeric       `db:"infant_price" json:"infantPrice"`
	StartDate                  pgtype.Timestamptz   `db:"start_date" json:"startDate"`
	EndDate                    pgtype.Timestamptz   `db:"end_date" json:"endDate"`
	ExcludedDates              []pgtype.Timestamptz `db:"excluded_dates" json:"excludedDates"`
	SoldOutDates               []pgtype.Timestamptz `db:"sold_out_dates" json:"soldOutDates"`
	SpecificTerms              string               `db:"specific_terms" json:"specificTerms"`
	IsActive                   bool                 `db:"is_active" json:"isActive"`
}

type ServiceStopOrdering struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Created    pgtype.Timestamptz `db:"created" json:"created"`
	Modified   pgtype.Timestamptz `db:"modified" json:"modified"`
	ServiceID  pgtype.UUID        `db:"service_id" json:"serviceId"`
	LocationID pgtype.UUID        `db:"location_id" json:"locationId"`
	Ordering   int32              `db:"ordering" json:"ordering"`
}

type ServiceTermsConditions struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Created         pgtype.Timestamptz `db:"created" json:"created"`
	Modified        pgtype.Timestamptz `db:"modified" json:"modified"`
	ServiceID       pgtype.UUID        `db:"service_id" json:"serviceId"`
	Ordering        int32              `db:"ordering" json:"ordering"`
	GeneralTerms    pgtype.Text        `db:"general_terms" json:"generalTerms"`
	LuggageNotes    pgtype.Text        `db:"luggage_notes" json:"luggageNotes"`
	AdditionalNotes pgtype.Text        `db:"additional_notes" json:"additionalNotes"`
}

type Session struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Created            pgtype.Timestamptz `db:"created" json:"created"`
	Modified           pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted            pgtype.Timestamptz `db:"deleted" json:"deleted"`
	AccountID          pgtype.UUID        `db:"account_id" json:"accountId"`
	ClientID           pgtype.UUID        `db:"client_id" json:"clientId"`
	ClientAgent        string             `db:"client_agent" json:"clientAgent"`
	ClientIp           string             `db:"client_ip" json:"clientIp"`
	ClientBundleID     pgtype.Text        `db:"client_bundle_id" json:"clientBundleId"`
	AccessToken        string             `db:"access_token" json:"accessToken"`
	RefreshToken       string             `db:"refresh_token" json:"refreshToken"`
	AccessTokenExpiry  pgtype.Timestamptz `db:"access_token_expiry" json:"accessTokenExpiry"`
	RefreshTokenExpiry pgtype.Timestamptz `db:"refresh_token_expiry" json:"refreshTokenExpiry"`
	IsDeviceApp        bool               `db:"is_device_app" json:"isDeviceApp"`
}

type Station struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Created     pgtype.Timestamptz `db:"created" json:"created"`
	Modified    pgtype.Timestamptz `db:"modified" json:"modified"`
	Deleted     pgtype.Timestamptz `db:"deleted" json:"deleted"`
	LocationID  pgtype.UUID        `db:"location_id" json:"locationId"`
	Name        string             `db:"name" json:"name"`
	Address     string             `db:"address" json:"address"`
	Code        string             `db:"code" json:"code"`
	Description string             `db:"description" json:"description"`
	Latitude    string             `db:"latitude" json:"latitude"`
	Longitude   string             `db:"longitude" json:"longitude"`
	StopID      string             `db:"stop_id" json:"stopId"`
	ZoneID      string             `db:"zone_id" json:"zoneId"`
	StopUrl     string             `db:"stop_url" json:"stopUrl"`
	IsActive    bool               `db:"is_active" json:"isActive"`
}

type StationImage struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Created   pgtype.Timestamptz `db:"created" json:"created"`
	Modified  pgtype.Timestamptz `db:"modified" json:"modified"`
	StationID pgtype.UUID        `db:"station_id" json:"stationId"`
	Ordering  int32              `db:"ordering" json:"ordering"`
	Image     string             `db:"image" json:"image"`
	ImageInfo string             `db:"image_info" json:"imageInfo"`
}

type StationProductType struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Created       pgtype.Timestamptz `db:"created" json:"created"`
	Modified      pgtype.Timestamptz `db:"modified" json:"modified"`
	StationID     pgtype.UUID        `db:"station_id" json:"stationId"`
	ProductTypeID pgtype.UUID        `db:"product_type_id" json:"productTypeId"`
}
